version: "3"

services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:2022.04.3
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    env_file:
      - ./pihole.env
    volumes:
      - ./pihole-etc/:/etc/pihole
      - ./pihole-dnsmasq.d/:/etc/dnsmasq.d
    dns: '8.8.8.8'
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:1.21.6-alpine
    depends_on:
      pihole:
        condition: service_healthy
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:      
      - ./nginx-conf:/etc/nginx/conf.d/:ro
      - ./certbot/conf:/etc/nginx/ssl/:ro
      - ./certbot/www:/var/www/certbot/:ro   
    restart: unless-stopped

  certbot:
    container_name: certbot
    depends_on:
      - nginx
    image: certbot/certbot:nightly
    volumes:
      - ./certbot/conf:/etc/letsencrypt/:rw
      - ./certbot/www:/var/www/certbot/:rw
    command: certbot certonly --webroot -w /var/www/certbot --force-renewal \
             --email faikasil.dikmen@gmail.com -d *.levopslab.com --agree-tos